kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: dev-bogota-ops-autoscaling
  namespace: cp4i
  labels:
    app: dev-bogota-ops
spec:
  scaleTargetRef:
    kind: Deployment
    name: dev-bogota-ops
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 98
