apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: dev-bogota-ops
spec:
  version: 11.0.0.11-r2
  license:
    accept: true
    license: L-APEH-BY5CY7
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  barURL: >-
    https://integration-dashboard-dash:3443/v1/directories/TESTBAR?58389ed0-44e9-4951-a453-1917aeee563d
  configurations:
    - extensions.zip
    - odbc-tskdb
    - credenciais-db2
  designerFlowsOperationMode: disabled
  service:
    endpointType: http
  router:
    timeout: 120s
  adminServerSecure: true
  createDashboardUsers: true
  enableMetrics: true
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
