apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: dev-bogota-ops
  namespace: cp4i
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-BY5CY7
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: 11.0.0.11-r2
  barURL: >-
    https://integration-dashboard-dash:3443/v1/directories/TESTBAR?58389ed0-44e9-4951-a453-1917aeee563d
  configurations:
    - extensions.zip
    - odbc
    - credenciais-db2
  tracing:
    enabled: true
    namespace: cp4i
